-- Document substrate (Slice 2 of the docs/workflows feature).
--
-- Taylor's ops are document-centric ([[feedback-docs-first]]) — POs, WOs,
-- sign-in sheets, contracts arrive as PDFs and the invoices she sends are
-- PDFs too. Travis must treat documents as first-class inputs/outputs,
-- not just side-effect artifacts. This migration adds the storage layer
-- core ships: a typed document table, content-addressed file storage
-- referenced by hash, and an N:M link table relating documents to
-- entities (a single PO may attach to a contract + engagement + school).
--
-- The actual file bytes live on disk under <app_data>/documents/
-- {hash_prefix}/{full_hash}{ext} — keeps the SQLite file small and lets
-- us dedup identical drops automatically. The DB stores metadata only.

CREATE TABLE IF NOT EXISTS document (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    workspace_id        INTEGER NOT NULL DEFAULT 1,

    -- The document kind — used by pack-specific extractors to know
    -- which schema to apply. Generic for core ("file"); packs
    -- introduce typed kinds ("po", "wo", "signed_sheet", "invoice",
    -- "contract", "quote"). Free text — packs validate their own.
    kind                TEXT NOT NULL DEFAULT 'file',

    -- User-facing display name. Defaults to the file's original
    -- basename; Taylor can rename in chat or in the docs surface.
    display_name        TEXT NOT NULL,

    -- Original filename at ingest time — kept for audit / reference,
    -- even if display_name is later edited.
    original_filename   TEXT NOT NULL,

    -- SHA-256 of the file bytes, lowercase hex. Drives content-
    -- addressed storage path and dedup on ingest.
    content_hash        TEXT NOT NULL,

    -- Path under <app_data>/documents/, including the hash-prefix
    -- directory. Example: "a3/a3f7c9...pdf". Relative so the storage
    -- root can move between machines.
    relative_path       TEXT NOT NULL,

    -- File size in bytes — for storage telemetry and quota planning.
    size_bytes          INTEGER NOT NULL,

    -- MIME type from the file extension at ingest. PDFs are the
    -- common case for v1; later slices accept images / spreadsheets.
    mime_type           TEXT NOT NULL DEFAULT 'application/octet-stream',

    -- Extraction state lifecycle:
    --   pending   — file ingested, extraction not yet attempted
    --   extracted — extraction succeeded, extracted_json populated
    --   failed    — extraction attempted and failed (see error_msg)
    --   skipped   — extraction not applicable (e.g., generated by Travis)
    ingest_status       TEXT NOT NULL DEFAULT 'pending'
        CHECK (ingest_status IN ('pending','extracted','failed','skipped')),

    -- Structured extraction output, populated by Slice 3. JSON shape
    -- varies by document kind — each pack owns its extraction schema.
    extracted_json      TEXT,

    -- Last extraction error (if ingest_status = 'failed').
    extraction_error    TEXT,

    -- Where this document came from:
    --   user_dropped         — Taylor dropped it via drag-drop or attach
    --   generated_by_travis  — Travis produced the PDF (closes the
    --                          round-trip loop in Slice 4)
    --   imported             — bulk import from a folder (future)
    source              TEXT NOT NULL DEFAULT 'user_dropped'
        CHECK (source IN ('user_dropped','generated_by_travis','imported')),

    -- Optional: the conversation this document was ingested under,
    -- so retrieval can show "you dropped this PDF on March 3 while
    -- discussing PS498".
    conversation_id     INTEGER,

    -- Optional: the active workflow at ingest time, so the dialogue
    -- manager can attribute the drop to a specific slot.
    workflow_state_id   INTEGER,

    created_at          TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_document_workspace ON document(workspace_id);
CREATE INDEX IF NOT EXISTS idx_document_hash ON document(content_hash);
CREATE INDEX IF NOT EXISTS idx_document_kind ON document(kind, workspace_id);
CREATE INDEX IF NOT EXISTS idx_document_conversation ON document(conversation_id);
CREATE INDEX IF NOT EXISTS idx_document_workflow ON document(workflow_state_id);

-- N:M between documents and entities. A PO might attach to a school
-- (the buyer), a contract, and an engagement — three rows in this
-- table for one document. Soft FKs (no CASCADE) so entity deletion
-- doesn't silently drop attachments.
CREATE TABLE IF NOT EXISTS document_link (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    document_id     INTEGER NOT NULL REFERENCES document(id) ON DELETE CASCADE,
    entity_id       INTEGER NOT NULL,
    -- The relationship kind. Examples: 'attached_to' (generic),
    -- 'extracted_from' (this entity was created by extracting this doc),
    -- 'generated_for' (this doc was generated for this entity).
    relation_kind   TEXT NOT NULL DEFAULT 'attached_to',
    created_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(document_id, entity_id, relation_kind)
);

CREATE INDEX IF NOT EXISTS idx_document_link_doc ON document_link(document_id);
CREATE INDEX IF NOT EXISTS idx_document_link_entity ON document_link(entity_id);
